### ISSUE TITLE
Font Family not changed

### ISSUE THREAD

**Issue by arpitjindal97** [PDConSec/vsc-print#181] opened 2023-01-29 23:10 UTC
I'm trying to print my code.

My editor font family is below:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/15676216/215360965-d4973b4f-fef4-47a6-a1db-a80cac2ac6dc.png">

Still the print document has "Fira Code, monospace"

**Comment by PeterWone** [comment] 2023-01-30 01:31
To help me reproduce this, tell me how you determined that Fira Code is being used in the browser.

Also, managing the translation of docs and UI is making our release cycle much slower which makes it hard to respond quickly to this kind of problem. I hope this isn't too inconvenient, please bear with us while we figure out a more efficient process.

**Comment by arpitjindal97** [comment] 2023-01-30 23:53
I did inspect element and scrolled down in the Styles tab found out Fira Code is set by line-number.css which is active

**Comment by PeterWone** [comment] 2023-01-31 08:18
Thank you. That's very helpful, I suspect I know what's going on (it will probably be the order in which the stylesheet links are added). All things being equal it will be fixed in the next release.

**Comment by arpitjindal97** [comment] 2023-01-31 10:25
Also, I'm unable to change font-size on Markdown

**Comment by PeterWone** [comment] 2023-02-22 10:23
Rendered Markdown is controlled by a stylesheet. It is unaffected by your editor font-size because this is used only for rendering source code.

**Comment by PeterWone** [comment] 2023-02-22 10:23
This is fixed in the next release.

**Closed by PeterWone** 2023-02-22 10:23 UTC
