### ISSUE TITLE
Inline math equations does not work

### ISSUE THREAD

**Issue by araujo-fernando** [PDConSec/vsc-print#342] opened 2024-08-23 13:22 UTC
Hello! 

I am trying to render a markdown with inline expressions, however is failing to do so.
Expressions surrounded by `$$ $$ ` are rendered normally.
It seems this should be working since version 0.12.15 (#324).
I tried to roll back to that version and it also didn`t work,

Can I have some help please? 😄 

![image](https://github.com/user-attachments/assets/b70eb9ab-bd15-4eb0-861e-acaece784f9c)

VS Code:
Version: 1.92.2 (system setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Print: 
v0.12.16

Edge:
Version 127.0.2651.74 (oficial) (64 bits)

**Comment by PeterWone** [comment] 2024-08-23 22:52
Because it is quite common to use the dollar sign in normal text I changed the marker for inline katex to `$%` closed by `%$`. There is an outstanding ticket for documentation updates. We apologise for the inconvenience.

Your picture was clear, but it would have made reproducing quicker if you pasted the problem source into a fenced block in the issue. If you want to put a fenced block sample in a fenced block just used more backticks for the outermost fence.

```markdown
# Value in use - Heat by Heat

## Sets

$%B%$: BONs

$%L%$: Layers

$%R%$: Railcars

# Subsets

$%S_l \supset S%$: scraps allowed in layer $%l%$

$%S_r \supset S%$: scraps available in railcar $%r%$
```
![image](https://github.com/user-attachments/assets/5badd704-4f68-4f50-af4d-1d05d12fefe3)

**Comment by PeterWone** [comment] 2024-08-23 23:10
I notice that for Subsets the Latex is rendered but the following text is not. I'll look into that.

**Comment by hykhhijk** [comment] 2024-09-21 08:12
I use $equation$ form too. It looks like all 0.12~ versions don't work with this.

So I rollback to 0.11.19 version and $works again
![image](https://github.com/user-attachments/assets/e2caf061-75e1-47c7-957d-554f7bff2f72)
In extionsion tab if you click that you can choose version to downgrade.

**Comment by PeterWone** [comment] 2024-09-23 00:49
We think it's related to another reported issue for which we have a fix that will be released soon.

**Comment by PeterWone** [comment] 2024-09-28 22:42
Found it! Coming in next release.
![image](https://github.com/user-attachments/assets/9288cda5-49b4-4e4e-b943-a0a74d7b08f2)

**Closed** 2024-09-29 09:58 UTC
