### ISSUE TITLE
Print icon is not shown

### ISSUE THREAD

**Issue by Elsayed-Mohamed685** [PDConSec/vsc-print#282] opened 2023-11-15 20:38 UTC
**print icon is not shown.
also after select the code an right click there is no print option in the menu!!**

**Comment by PeterWone** [comment] 2023-11-15 21:46
There are two ways this can happen.

1. Settings
2. Borked user profile

Here's a working installation. At top right appears the toolbar icon. This only appears when an editor has focus. I have selected some code and right-clicked on it. Print appears as the bottom item because that's how my settings are configured.

If yours is a fresh installation of Print then it won't be settings. I have experienced user profile damage myself. My solution was to un-install vscode, then delete the folder `%userprofile%\.vscode` then reinstall vscode and then all my extensions.  

1. Capture your extensions using the command line `code --list-extensions > extensions.cmd` 
2. Uninstall vscode
3. `del %userprofile%\.vscode`
4. Reboot if you don't trust Windows
5. Install vscode
6. Use vscode to edit `extensions.cmd`. It contains one extension identifier per line. Turn each line into an installation command. and then run it.

Suppose your extension list file contains this

```
mhutchie.git-graph
ms-azuretools.vscode-docker
ms-dotnettools.blazorwasm-companion
ms-dotnettools.csharp
```

You need to make it like this 

```
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.blazorwasm-companion
code --install-extension ms-dotnettools.csharp
```

![image](https://github.com/PDConSec/vsc-print/assets/5498936/14f79e38-1202-4d3a-9bcc-1dea973b625a)

## Check your settings

### Menu
![image](https://github.com/PDConSec/vsc-print/assets/5498936/2940e4f2-aa2f-4c74-863a-b07b5410f04e)

If you set this to None then Print will not appear in the menu.

### Toolbar icon

This setting turns the toolbar icon on or off.

![image](https://github.com/PDConSec/vsc-print/assets/5498936/cb68c887-1c9b-4d2c-9907-34cec35ff1c2)

**Comment by StefRe** [comment] 2024-05-16 13:49
same problem here: reinstalled everything after deleting `%userprofile%\.vscode` and `%appdata%\Code` but still no print icon (printing a cell from context menu or via command palette works, but I can't print the whole notebook)
![grafik](https://github.com/PDConSec/vsc-print/assets/19879328/bf3eafb0-0ae5-4e36-8c04-e7bd67785a9e)

Settings:
![grafik](https://github.com/PDConSec/vsc-print/assets/19879328/ade50699-670c-4b3e-a93a-fba102f0293f)


Print v0.11.19, VSCode v1.89.1, Windows 10

**Comment by StefRe** [comment] 2024-05-16 14:21
Mhm, I just noticed that the print icon is shown for `.py` file, it's just missing for `.ipynb` files. Is this by design that whole IPython notebooks cannot be printed or is it just a bug?

**Comment by PeterWone** [comment] 2024-05-16 21:48
> Mhm, I just noticed that the print icon is shown for `.py` files, it's just missing for `.ipynb` files. Is this by design that whole IPython notebooks cannot be printed or is it just a bug?

Neither. 

Python notebooks are not python files so you cannot just use the source code renderer on them.

The Print extension supports an API that allows you to define and register a document renderer and associate it with a file extension, allowing Print to render new document formats. So far nobody wants this enough to contribute.

**Comment by StefRe** [comment] 2024-05-17 06:42
Thanks for the quick reply and explanation. Yes, IPython notebooks are a list of cells that can be either Markdown or Python. Both types can be printed using the Print extension, so I imagine that it would be not too hard to print the whole notebook too (unfortunately, I'm a complete newbie when it comes to typescript/javascript).  

As a workaround I now export the notebook to html and print the html.

**Comment by PeterWone** [comment] 2024-05-17 08:12
Printing has two main aspects. There's document rendering, which produces HTML with stylesheets, and there's the machinery for delivering it to the browser, which is basically an embedded webserver that resolves resource requests in the context of a print session (so you can print one document, leave it open in a browser, click a different editor and print another document, and the resources for the two don't get mixed up).

For source code, vscode identifies the language of the active editor, and the source code document renderer passes this along with the file content to a library called highlightjs that does most of the work. Print doesn't do any special handling for Python, it relies completely on highlightjs.

For Markdown we hook into the internal rendering pipeline that vscode uses for the embedded Markdown preview, although we're getting ready to go our own way because Microsoft keeps making breaking changes.

To handle a document that _mixes them_ would be a lot more complicated. It's not out of the question, but it's non-trivial and since I'm not a user of these notebooks I don't have clear reliable expectations of behaviour or syntax, just what I learnt from initial investigation the last time someone wanted this. 

I'm pleased you have a workaround. If you ever decide you want something more integrated, I'll certainly support you in putting something together.

**Comment by PeterWone** [comment] 2024-07-07 01:53
I'm going to close this issue because it's environmental and has nothing to do with Print as such. 

Re printing notebooks see also #221

**Closed by PeterWone** 2024-07-07 01:53 UTC
